apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapih2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todoapih2
        image: vijaynvb/todoapp
        ports:
        - containerPort: 8081 


---

apiVersion: v1
kind: Service
metadata:
  name: svctodoh2api
spec:
  selector:
    app: todo
  ports:
    - port: 80        
      targetPort: 8081 
  type: LoadBalancer  
