name: 02-02-VMVerify
on: push
jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  my-second-job:
    runs-on: windows-latest
    steps:
      - run: echo "Bye World"
  my-third-job:
    runs-on: macos-latest
    steps:
      - run: echo "Bye World"
